# Generated by Django 6.0.5 on 2026-06-03 17:04

import apps.inventory.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalStorageCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorthand', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=50)),
                ('help_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('iupac', models.CharField(max_length=50)),
                ('cas', models.CharField(max_length=13, validators=[apps.inventory.models.validate_cas])),
                ('formula', models.CharField(max_length=50)),
                ('pubchem_cid', models.IntegerField()),
                ('synonyms', models.JSONField()),
                ('molecular_weight', models.DecimalField(decimal_places=3, max_digits=5)),
                ('is_organic', models.BooleanField()),
                ('storage_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.chemicalstoragecategories')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('barcode', models.CharField(max_length=80, unique=True)),
                ('manufacturer', models.CharField(max_length=20)),
                ('initial_quantity', models.IntegerField()),
                ('quantity_unit', models.CharField(choices=[('mL', 'mL'), ('L', 'L'), ('mg', 'mg'), ('g', 'g'), ('kg', 'kg')], max_length=2)),
                ('product_num', models.CharField(max_length=25)),
                ('date_received', models.DateField(auto_now=True)),
                ('date_opened', models.DateField(blank=True, null=True)),
                ('date_discarded', models.DateField(blank=True, null=True)),
                ('density', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('initial_weight', models.DecimalField(decimal_places=4, max_digits=8)),
                ('tare_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=3)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('Container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.container')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('barcode', models.CharField(max_length=75)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.location')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.location'),
        ),
        migrations.CreateModel(
            name='SDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=20)),
                ('drive_id', models.CharField(max_length=100)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('revision_number', models.IntegerField(blank=True, null=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.chemical')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='sds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.sds'),
        ),
        migrations.CreateModel(
            name='WeightReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=4, max_digits=8)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.container')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
