# Generated by Django 6.0.5 on 2026-06-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sds',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
