# Generated by Django 6.0.5 on 2026-06-13 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sds_is_uploaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutevent',
            old_name='Container',
            new_name='container',
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.locationtypes'),
        ),
    ]
