# Generated by Django 6.0.5 on 2026-06-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_container_checkoutevent_container_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutevent',
            name='action',
            field=models.CharField(choices=[('in', 'Check In'), ('out', 'Check Out')], max_length=3),
        ),
    ]
