# Generated by Django 6.0.5 on 2026-06-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_checkoutevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='barcode',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.location'),
        ),
    ]
