# Generated by Django 6.0.5 on 2026-06-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_location_barcode_alter_location_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalstoragecategories',
            name='shorthand',
            field=models.CharField(max_length=3),
        ),
    ]
