# Generated by Django 6.0.5 on 2026-06-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_chemicalstoragecategories_shorthand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='formula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='is_organic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='iupac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='molecular_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='pubchem_cid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='synonyms',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
