# Generated by Django 6.0.5 on 2026-06-15 19:28

import apps.inventory.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_chemical_formula_alter_chemical_is_organic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='cas',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[apps.inventory.models.validate_cas]),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.chemical')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.container')),
            ],
        ),
    ]
