# Generated by Django 6.0.5 on 2026-06-15 19:29

import apps.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_chemical_cas_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='cas',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[apps.inventory.models.validate_cas]),
        ),
    ]
