# Generated by Django 6.0.5 on 2026-06-16 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_chemical_cas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='storage_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.chemicalstoragecategories'),
        ),
    ]
