# Generated by Django 6.0.5 on 2026-06-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_chemical_storage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='molecular_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
