# Generated by Django 6.0.5 on 2026-06-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_chemical_molecular_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='iupac',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
