# Generated by Django 6.0.5 on 2026-06-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_chemical_iupac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='molecular_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
    ]
