# Generated by Django 6.0.5 on 2026-06-17 03:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_chemical_iupac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='barcode',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='date_received',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='container',
            name='initial_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='initial_weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='product_num',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('mL', 'mL'), ('L', 'L'), ('mg', 'mg'), ('g', 'g'), ('kg', 'kg')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='sds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.sds'),
        ),
    ]
