# Generated by Django 6.0.5 on 2026-06-17 03:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_container_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='date_received',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
