# Generated by Django 6.0.5 on 2026-06-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_container_date_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
