# Generated by Django 6.0.5 on 2026-06-17 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_container_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.container'),
        ),
    ]
