# Generated by Django 6.0.5 on 2026-06-17 18:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_ingredient_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='date_discarded',
            field=models.DateField(blank=True, null=True, verbose_name='discarded on'),
        ),
        migrations.AlterField(
            model_name='container',
            name='date_opened',
            field=models.DateField(blank=True, null=True, verbose_name='opened on'),
        ),
        migrations.AlterField(
            model_name='container',
            name='date_received',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='received on'),
        ),
        migrations.AlterField(
            model_name='container',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='density/specific gravity'),
        ),
        migrations.AlterField(
            model_name='container',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='expires on'),
        ),
        migrations.AlterField(
            model_name='container',
            name='initial_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='container',
            name='initial_weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='initial weight'),
        ),
        migrations.AlterField(
            model_name='container',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='manufacturer'),
        ),
        migrations.AlterField(
            model_name='container',
            name='product_num',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='product #'),
        ),
        migrations.AlterField(
            model_name='container',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('mL', 'mL'), ('L', 'L'), ('mg', 'mg'), ('g', 'g'), ('kg', 'kg')], max_length=2, null=True, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='container',
            name='sds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.sds', verbose_name='sds'),
        ),
        migrations.AlterField(
            model_name='container',
            name='tare_weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='container weight'),
        ),
    ]
