# Generated by Django 6.0.5 on 2026-06-18 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_container_date_discarded_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='container',
        ),
        migrations.AlterField(
            model_name='checkoutevent',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.container'),
        ),
        migrations.AlterField(
            model_name='checkoutevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='storage_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chemicals', to='inventory.chemicalstoragecategories'),
        ),
        migrations.AlterField(
            model_name='container',
            name='chemical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='containers', to='inventory.chemical'),
        ),
        migrations.AlterField(
            model_name='container',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='containers', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='chemical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory.chemical'),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='inventory.locationtypes'),
        ),
        migrations.AlterField(
            model_name='sds',
            name='chemical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sds', to='inventory.chemical'),
        ),
        migrations.AlterField(
            model_name='weightreading',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='inventory.container'),
        ),
        migrations.AlterField(
            model_name='weightreading',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='readings', to=settings.AUTH_USER_MODEL),
        ),
    ]
