# Generated by Django 6.0.5 on 2026-06-23 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_ingredient_container_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='chemical',
            new_name='mixture',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mixtures', to='inventory.chemical'),
            preserve_default=False,
        ),
    ]
