# Generated by Django 6.0.5 on 2026-06-29 23:56

from django.db import migrations, models
from django.utils.text import slugify

def add_slugs_to_containers(apps, schema_editor):
    Container = apps.get_model("inventory", "container")
    for c in Container.objects.all():
        slug = f'chem-{c.id}'
        c.slug = slugify(slug)
        c.save()

def reverse_add_slugs_to_containers(apps, schema_editor):
    Container = apps.get_model("inventory", "container")
    for c in Container.objects.all():
        c.slug = None
        c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_rename_chemical_ingredient_mixture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(add_slugs_to_containers, reverse_add_slugs_to_containers),
        migrations.AlterField(
            model_name='container',
            name='slug',
            field=models.SlugField(unique=True)
        )
    ]
