# Generated by Django 6.0.5 on 2026-07-01 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20260629_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutevent',
            name='related_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_in_event', to='inventory.checkoutevent'),
        ),
    ]
