# Generated by Django 6.0.5 on 2026-09-14 21:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_sds_container'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable, e.g. 'Location label (12mm)'. Not sent to the printer.", max_length=50)),
                ('kind', models.CharField(choices=[('container', 'Container'), ('location', 'Location')], max_length=20)),
                ('template_number', models.PositiveSmallIntegerField(help_text='The number assigned to this template in P-touch Transfer Manager (1-99).', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('media_width_mm', models.PositiveSmallIntegerField(choices=[(6, '6 mm'), (9, '9 mm'), (12, '12 mm'), (18, '18 mm'), (24, '24 mm'), (36, '36 mm')])),
            ],
            options={
                'ordering': ['kind', 'media_width_mm'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'media_width_mm'), name='unique_label_template_kind_media_width')],
            },
        ),
        migrations.CreateModel(
            name='LabelTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('barcode', 'Barcode'), ('text', 'Text')], max_length=20)),
                ('object_name', models.CharField(help_text="The object's name inside the template, as set in P-touch Editor (e.g. 'Barcode1').", max_length=50)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='inventory.labeltemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('template', 'role'), name='unique_label_template_field_role')],
            },
        ),
    ]
