# Generated by Django 6.0.5 on 2026-09-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_labeltemplate_labeltemplatefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sds',
            name='revision_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
