# Generated by Django 6.0.5 on 2026-09-23 21:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_alter_sds_revision_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalstoragecategories',
            name='families',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chemicalstoragecategories',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
