# Generated by Django 6.0.7 on 2026-10-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_flinn_storage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='density/specific gravity'),
        ),
    ]
