# Generated by Django 6.0.5 on 2026-06-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scanned_id',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('full', 'Full User'), ('guest', 'Guest')], default='full', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('lab_manager', 'Lab Manager'), ('coordinator', 'Coordinator'), ('stockroom', 'Stockroom'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
