# Generated by Django 6.0.5 on 2026-06-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_scanned_id_user_user_type_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='scanned_id',
            new_name='lipscomb_id',
        ),
    ]
