# Generated by Django 6.0.5 on 2026-09-02 20:09

from django.db import migrations, models


# "viewer" is renamed to "lab_assistant" (same concept, matches the new role
# name) — existing rows need to move over explicitly since Django doesn't
# rewrite data for a changed `choices` list. No reverse: rows created after
# this migration as "admin"/"faculty" have no equivalent under the old
# 4-role scheme, so a full round-trip isn't meaningful — only the
# viewer/lab_assistant rename is undone.
def rename_viewer_to_lab_assistant(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(role="viewer").update(role="lab_assistant")


def rename_lab_assistant_to_viewer(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(role="lab_assistant").update(role="viewer")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_scanned_id_user_lipscomb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lab_manager', 'Lab Manager'), ('coordinator', 'Coordinator'), ('faculty', 'Faculty'), ('stockroom', 'Stockroom Worker'), ('lab_assistant', 'Lab Assistant')], default='lab_assistant', max_length=20),
        ),
        migrations.RunPython(rename_viewer_to_lab_assistant, rename_lab_assistant_to_viewer),
    ]
