# Generated by Django 6.0.5 on 2026-09-28 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_status', models.CharField(choices=[('none', 'Not sent'), ('pending', 'Pending'), ('created', 'Created'), ('failed', 'Failed')], default='none', max_length=10)),
                ('github_issue_number', models.PositiveIntegerField(blank=True, null=True)),
                ('github_issue_url', models.URLField(blank=True)),
                ('github_error', models.TextField(blank=True)),
                ('summary', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('impact', models.CharField(choices=[('blocking', "I can't continue"), ('annoying', "It's annoying but I can work around it"), ('minor', 'Minor / cosmetic')], default='annoying', max_length=10)),
                ('route', models.CharField(blank=True, max_length=500)),
                ('app_version', models.CharField(blank=True, max_length=64)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_status', models.CharField(choices=[('none', 'Not sent'), ('pending', 'Pending'), ('created', 'Created'), ('failed', 'Failed')], default='none', max_length=10)),
                ('github_issue_number', models.PositiveIntegerField(blank=True, null=True)),
                ('github_issue_url', models.URLField(blank=True)),
                ('github_error', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('confusing', 'Something was confusing'), ('tedious', 'Something is slow or tedious'), ('idea', 'I have an idea'), ('other', 'Other')], max_length=10)),
                ('route', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('may_contact', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('done', 'Done')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
